### ISSUE TITLE
Playlists don't work when progressing naturally, but skips are fine

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-ocp-audio-plugin#123]
Playlists work if I don't let a track finish. For example, I can skip to the next track, see all the tracks, etc, but when I finish listening to one song it shows:

```sh
2024-08-04 20:51:48.319 - audio - ovos_audio.audio:track_start:210 - DEBUG - New track coming up!
...snip
2024-08-04 20:55:38.563 - audio - ovos_audio.audio:track_start:217 - DEBUG - End of playlist!
```

**Comment by mikejgray** [comment]
Confirmed on both my Mac and on my Mark 1 (Pi 4 hacked upgrade)

**Comment by goldyfruit** [comment]
Same here. The playlist stopped after the first song finishes.

**Comment by mikejgray** [comment]
Fixed!
