### ISSUE TITLE
settings storage seems to be ambiguous

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/ovos-ocp-audio-plugin#43]
even though the ocp plugin uses XDG_CONFIG_HOME for its settings (.config/mycroft/apps/ovos.common_play/settings.json), sometimes it tries to save into the package library
```
21:56:52.501 - audio - ovos_utils.skills.settings:save_settings:118 - ERROR - error saving skill settings to /usr/lib/python3.10/site-packages/ovos_plugin_common_play/ocp/settings.json
```

**Comment by JarbasAl** [comment]
the xdg path was a recent change in last release, the OVOSAbstractApp and OVOSSkill classes have been unified in workshop, at same time OCP was refactored to follow a standard with all apps, perhaps some issue was introduced here

**Comment by emphasize** [comment]
And there is more to it. After i changed `app_view_timeout_enabled` in the GUI menu, the config was written just fine. GUI wasn't reacting to the changes and i switched between `pause` and `all` i went back and the setting was an empty dict.

Anything i can test?

**Comment by emphasize** [comment]
Goes way back. don't think this is still an issue.
