### ISSUE TITLE
[BUG] No clear way of exiting the music application

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-ocp-audio-plugin#55]
### Description

There is no clear method or command of exiting the music player application and returning to the main Neon dashboard clock screen (on mycroft II device). 

### Other Notes

this may just be a documentation flaw but after trying numerous voice commands such as "cancel music" "exit music" "turn off music", "exit player" "exit music player" nothing so far has worked. 

This was originally submitted by @msmick https://github.com/NeonGeckoCom/skill-free_music_archive/issues/11

**Comment by JarbasAl** [comment]
- in ovos shell pull down and go to homescreen directly
- use the auto timeout config option to return automatically after X time

suggested voice commands should probably be made a stop intent for OCP however

docs here for reference https://openvoiceos.github.io/community-docs/OCP/

**Comment by NeonDaniel** [comment]
I think a "close" button, similar to the homeassistant GUI might help here and/or returning to the homescreen on "stop" or with a dedicated intent to return to the homescreen

**Comment by AIIX** [comment]
I can add an exit button similar to other apps to the UI optionally can be hidden so its only shown when the screen is tapped if we don't want to make it prominent and change the current UI look and feel, the second question is what does the exit button do in terms of behaviour, i.e. close the media player as in if playing audio via the GUI backend or continue playback and only close the UI the widget will become active once that happens, also in terms of Video it wouldn't make much sense to continue video playback so completely quit the app ? @NeonDaniel If I can get a behaviour defined would be helpful

**Comment by NeonDaniel** [comment]
Related, there's no "stop" button in the player UI; this could be another option to stop playback and return to the homescreen (or OCP search or results page?).

Some ideas:

- Stop button which stops current playback and clears the queue. This could return to the OCP search screen and wait for player timeout, or immediately return to the homescreen.

- Close/exit button immediately closes OCP and returns to the homescreen. My preference would be for audio playback to continue with the homescreen widget and for video to pause, similar to the behavior on Android (minus the floating video player)
