### ISSUE TITLE
"resume" or "continue" results in a spoken error

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-ocp-audio-plugin#65]
When media is paused, "resume" or "continue" responds with "what would you like to play next" and then a spoken error after the user responds.

2 bugs:
 - [x] "resume" should just continue the paused track
 - [ ] if there isn't a track playing or the end of the playlist is reached, the current behavior should handle the user's response and generate a new playlist.

**Comment by NeonDaniel** [comment]
#65 resolves 'resume' behavior. The remaining "issue" is whether stopped playback can be resumed or if it should prompt the user.

**Comment by JarbasAl** [comment]
maybe works with the new pipeline https://openvoiceos.github.io/ovos-technical-manual/OCP_pipeline/ + #112
