### ISSUE TITLE
When there is no high confidence match, every OCP skill speaks an error

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-ocp-audio-plugin#81]
I've noticed during testing of the Plex skill that if OCP doesn't get a high confidence match back from a skill, canceling the other searches, every single OCP skill will speak a failure. This is compounded when you have a failure for a specific MediaType and then another failure for MediaType.GENERIC.

Ideally OCP would aggregate all the failures into a single spoken failure.

**Comment by NeonDaniel** [comment]
Is this currently reproducible? I seem to always get some kind of match or a spoken "I don't know how to play..."

**Comment by mikejgray** [comment]
It may not be. It's been a while since I heard it, and it may have been due to broken skills...

**Comment by JarbasAl** [comment]
maybe works with the new pipeline https://openvoiceos.github.io/ovos-technical-manual/OCP_pipeline/ + #112
