### ISSUE TITLE
All media play requests loop (silently) until ovos restart

### ISSUE THREAD

**Issue by ShuffleBit** [OpenVoiceOS/ovos-ocp-audio-plugin#84]
Any attempt to play media (local media, news, etc) starts a neverending loop of attempts to play the media. No errors, no playing of the media, and continues until ovos is restarted.

raspbian-ovos-dev, rpi4b, no TV, ovos-plugin-common-play==0.0.6a1

`May 26 06:16:44 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:44.250 - audio - ovos_plugin_common_play.ocp.media:extract_stream:461 - INFO - OCP plugins metadata: {'uri': 'https://freemusicarchive.org/track/JoshWoodward-TSL-NoVox-102-Go/stream/'}
May 26 06:16:48 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:48.196 - audio - ovos_utils.file_utils:resolve_resource_file:145 - WARNING - Expected a dict config and got None. This configfallback behavior will be deprecated in a future release
May 26 06:16:48 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:48.244 - audio - ovos_utils.file_utils:resolve_resource_file:145 - WARNING - Expected a dict config and got None. This configfallback behavior will be deprecated in a future release
May 26 06:16:48 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:48.381 - audio - ovos_plugin_common_play.ocp.media:handle_track_state_change:512 - INFO - TrackState changed: <TrackState.PLAYING_AUDIOSERVICE: 21>
May 26 06:16:48 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:48.437 - audio - ovos_plugin_common_play.ocp.media:handle_track_state_change:512 - INFO - TrackState changed: <TrackState.QUEUED_AUDIOSERVICE: 31>
May 26 06:16:48 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:48.656 - audio - ovos_plugin_common_play.ocp.media:extract_stream:461 - INFO - OCP plugins metadata: {'uri': 'https://freemusicarchive.org/track/JoshWoodward-TSL-NoVox-102-Go/stream/'}
May 26 06:16:52 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:52.694 - audio - ovos_utils.file_utils:resolve_resource_file:145 - WARNING - Expected a dict config and got None. This configfallback behavior will be deprecated in a future release
May 26 06:16:52 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:52.729 - audio - ovos_utils.file_utils:resolve_resource_file:145 - WARNING - Expected a dict config and got None. This configfallback behavior will be deprecated in a future release
May 26 06:16:52 raspOvos ovos-systemd-audio[810]: 2023-05-26 06:16:52.895 - audio - ovos_plugin_common_play.ocp.media:handle_track_state_change:512 - INFO - TrackState changed: <TrackState.PLAYING_AUDIOSERVICE: 21>`

Audio config is default and doesn't paste into a code block well.

**Comment by JarbasAl** [comment]
what platform is this in? do you have any actual audio playback plugins installed?

eg, https://github.com/OpenVoiceOS/ovos-vlc-plugin or https://github.com/OpenVoiceOS/ovos-audio-plugin-simple ?

**Comment by ShuffleBit** [comment]
This is the raspbian-ovos-dev image running headless, so defaults: ovos_common_play, ovos_audio_simple, and ovos_vlc. Default "Audio" config, so all are active, and ovos_common_play is default.

ovos-plugin-common-play==0.0.6a1
ovos-audio-plugin-simple-0.0.2a3
ovos-plugin-vlc-0.0.2a2

Interesting thing, you asked about them so I upgraded ovos-audio-plugin-simple and ovos-plugin-vlc and the problem evolved: now I get:

`07:08:49.074 - audio - ovos_plugin_common_play.ocp.player:_get_preferred_audio_backend:375 - ERROR - Preferred audio service backend not installed`

And it's looping, but this is an improvement. What preferred backend is it expecting?

**Comment by ShuffleBit** [comment]
I don't see a clean path around this. If ocp recognizes that there's no dbus available, it can fork/exec a cmus process and use pycmus' api to control playback via cmus' default unix socket with messages from ovos' message bus. That does nothing for streaming internet audio.

It's solvable, but not in a clean robust way.

I'm going to close this.

**Comment by JarbasAl** [comment]
OCP should work headlessly, while we focused on the GUI to allow video playback it should work headlessly and started as fully headless project

We focused on the GUI aspect as we wanted an alternative for the mk2 as soon as it came out, so we were ready for it, but a fully headless reference image is something we just now started focusing on, with raspbian-ovos being the initial community effort to get that going as a replacement for picroft

the buildroot image will have a headless rpi3 compatible image version soon, the voice only experience will improve a lot once we get there and include a full headless system in our tests, that should then uncover these issues that happen only under certain configs and package combinations. currently most components are only tested individually (with a lot of room for improvement)

now some clarifications about OCP itself, or at least what should be happening:
- if a gui is not available it will then discard video only results if any
- if gui is not available it will delegate to the audio subsystem, that is where the audio plugins come in
- simple audio plugin is very limited as you noticed, but it is the default one with less dependencies that should be able to run everywhere
- https://github.com/OpenVoiceOS/ovos-vlc-plugin (most tested and recommended for now)
- https://github.com/OpenVoiceOS/ovos-audio-plugin-cmus  (untested, just a code backup of a old unfinished implementation)
- https://github.com/OpenVoiceOS/ovos-mplayer-plugin (minimally tested, port of old implementation)
- prefered audio backend setting is a ordered list of audio plugins to be used
- plugins report what uri types they can play, if unsupported the next on the list is tried
- the dbus connection is optional and only needed for MPRIS integration
- MPRIS provides voice control and awareness of other players running in the system, eg, control spotify app by voice
- MPRIS provides integration with KDEConnect and your phone

**Comment by ShuffleBit** [comment]
> OCP should work headlessly

Yes, I looked through the code. It doesn't, currently. I couldn't find out why it loops forever but I didn't look very hard.

I'm already leaning toward ovos over all other options at this point. It's elegant.

I'm going to look at the cmus plugin. Thanks for the links.

I'm leaving this closed because otherwise, I _should_ request a pull, and then I'd _have_ to fix the looping, and then I'd be pulled in for eternity and a bit.

**Comment by tarikki** [comment]
I ran into the exact same issue with the following setup:
- raspberry pi 4
- ubuntu
- everything running in virtualenvs because I didn't want the docker overhead

What solved it was the `'disable_mpris': true`. I'll make a small PR and add this to the documentation regarding troubleshooting audio [here](https://openvoiceos.github.io/community-docs/troubleshooting_audio/).
