### ISSUE TITLE
OCP GUI stays up until dismissed after playing a single track

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-ocp-audio-plugin#98]
I have a use case where I've set up my device to play the doorbell sound when my doorbell rings. I'm using OCP to do that, with a 100% confidence match and a single file playlist. The problem is that after playing the sound, the empty OCP player screen stays up until I manually dismiss it.

Ideally the player screen would either:
1. Dismiss itself after x seconds/minutes of no playback with an empty playlist
2. Have an option in its bus message to time the player screen out after a period of time

**Comment by JarbasAl** [comment]
OCP is meant for media, for a doorbell sound you should use `self.play_audio(uri, instant=True)`

the player should return to homescreen after 30 seconds, the 30 seconds are there to allow the user to browse search results and select another track

without homescreen i think the player never exits

**Comment by mikejgray** [comment]
What about via bus? This is coming from Node-RED. Also, it is not timing out after 30 seconds. 🙂

**Comment by NeonDaniel** [comment]
This is configurable behavior; from the OCP home screen -> settings there are options to enable timeout and set the duration. Is that working for you and we just need to update default behavior in images/distributions?

**Comment by mikejgray** [comment]
I’ll test today and see, I had no idea there was a configuration option for that. Thank you!

**Comment by mikejgray** [comment]
Yep, that did indeed do the trick. Might be good to update as a default, but no reason to keep this issue open.
